pipeline {
  agent {
    label 'vetsgov-general-purpose'
  }

  environment {
    PROM_URL   = "${promurl}"
    PROM_QUERY = "${promquery}"
  }

  stages {
    stage('Create Report') {
      steps {
        timeout(time: 20, unit: 'MINUTES') {
          dir("loadtest-model") {
            script {
              dockerImage = docker.build('loadtest-model')
              args = "-v ${pwd()}:/report"
              dockerImage.inside(args) {
                sh 'loadtest-model'
              }
            }
          }
        }
      }
    }

    stage ('Archive Graphics') {
      steps {
        archiveArtifacts (artifacts: 'loadtest-model/*.png, loadtest-model/*.html')
        publishHTML (target: [
          allowMissing: false,
          alwaysLinkToLastBuild: false,
          keepAll: true,
          reportDir: 'loadtest-model',
          reportFiles: 'report.html',
          reportName: "Load Test Report"
        ])
      }
    }
  }

  post {
    always {
      deleteDir()
    }
  }
}