pipeline {
  agent {
    label 'vetsgov-general-purpose'
  }

  stages {
    stage('Create PDF') {
      steps {
        timeout(time: 20, unit: 'MINUTES') {
          dir("dashshot") {
            script {
              dockerImage = docker.build('dashshot')
              args = "-v ${pwd()}:/pdf"
              dockerImage.inside(args) {
                sh 'node /app/index.js'
              }
            }
          }
        }
      }
    }

    stage('Slack Results') {
      steps {
        withCredentials([string(credentialsId: 'slack-dashboard-token', variable: 'TOKEN')]) {
          dir("dashshot") {
            sh "curl -s -F file=@'kudos.pdf' -F channels='kudos-team' -F title='Kudos Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/1Jtp5YJsxzdRgApBIbcDMx5420U1VsKVt' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'rainbows.pdf' -F channels='rainbows-team' -F title='Rainbows Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/1OfD78MumK5roK7iBByiQv2mv271sKeac' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'unicorns.pdf' -F channels='unicorns-team' -F title='Unicorns Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/14Gv0B2uVXgK8_U4IPnuHP43ZMDA0qJft' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'nebula.pdf' -F channels='nebula' -F title='Nebula Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/1xsr2zq9vG8LNw0qwCG7bXX2L6APtGIR-' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'exec.pdf' -F channels='vetsdotgov' -F title='Vets.gov Weekly Executive Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/1GX0vKX93p84bqLK3sL5Bv7JusOay6jl7' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
          }
        }
      }
    }
  }

  post {
    always {
      deleteDir()
    }
    success {
      slackSend message: "Dashboard PDF distribution succeeded", color: "good", channel: "analytics-deploys"
    }
    failure {
      slackSend message: "<!here> Dashboard PDF distribution *FAILED*!", color: "danger", channel: "analytics-deploys"
    }
  }
}
