pipeline {
  agent {
    label 'vetsgov-general-purpose'
  }

  stages {
    stage('Create PDF') {
      steps {
        dir("dashshot") {
          script {
            dockerImage = docker.build('dashshot')
            args = "-v ${pwd()}:/pdf"
            dockerImage.inside(args) {
              sh 'node /app/index.js'
            }
          }
        }
      }
    }

    stage('Slack Results') {
      steps {
        withCredentials([string(credentialsId: 'slack-dashboard-token', variable: 'TOKEN')]) {
          dir("dashshot") {
            sh "curl -s -F file=@'kudos.pdf' -F channels='kudos-team' -F title='Kudos Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/0B-eryOVvbpHbcUNSbTlnWjZaVzA' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'rainbows.pdf' -F channels='rainbows-team' -F title='Rainbows Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/0B-eryOVvbpHbR3o4bDBfLTZFSmM' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
            sh "curl -s -F file=@'unicorns.pdf' -F channels='unicorns-team' -F title='Unicorns Weekly Dashboard' -F initial_comment='Interactive URL: https://datastudio.google.com/open/13_08yLsP1ncNgyWr5Ug__-fXEBCVjRs2' -F 'token=${TOKEN}' https://slack.com/api/files.upload"
          }
        }
      }
    }
  }

  post {
    always {
      deleteDir()
    }
    success {
      slackSend message: "Dashboard PDF distribution succeeded", color: "good", channel: "analytics-deploys"
    }
    failure {
      slackSend message: "<!here> Dashboard PDF distribution *FAILED*!", color: "danger", channel: "analytics-deploys"
    }
  }
}
