pipeline {
  agent {
    label 'vetsgov-general-purpose'
  }

  stages {
    stage('Create PDF') {
      steps {
        dir("dashshot") {
          script {
            dockerImage = docker.build('dashshot')
            args = "-v ${pwd()}:/pdf"
            dockerImage.inside(args) {
              sh 'node /app/index.js'
            }
          }
        }
      }
    }

    stage('Slack Results') {
      steps {
        slackSend message: "Dashboard Snapshot for Rainbows",
          channel: "analytics-deploys"
      }
    }
  }

  post {
    always {
      deleteDir()
    }
  }
}
